### ISSUE TITLE
Batch Processing

### ISSUE THREAD

**Issue by shakna-israel** [mlhubber/colorize#5]
Is there a way to run this without having a window pop up for every image?

I have several hundred thousand images I don't like to run a best guess against.

**Comment by gjwgit** [comment]
Thanks for the suggestion @shakna-israel.

As a workaround for now edit the file ~/.mlhub/colorize/apply.py to comment out the line that calls plot_bw_color_comparison(). That is replace:

`  plot_bw_color_comparison(gray, cv.cvtColor(color, cv.COLOR_BGR2RGB))`

with

`  # plot_bw_color_comparison(gray, cv.cvtColor(color, cv.COLOR_BGR2RGB))`

In the meantime I will update the package to be more command line friendly.

**Comment by gjwgit** [comment]
Suggest renaming the apply command to be test, and add a new color command that will be more command line friendly - no output except for the file name pairs: input and output.

**Comment by gjwgit** [comment]
Updated to be more command line friendly #3fb40942ba13c073b390cccd2f2a7fc9087df45a
