### ISSUE TITLE
Cannot import name 'get_cmd_cwd' from 'mlhub.utils' 

### ISSUE THREAD

**Issue by Herzbergh** [mlhubber/colorize#8]
ml color colorize testcolor.png 
Traceback (most recent call last):
  File "/userm/.mlhub/colorize/color.py", line 30, in <module>
    from mlhub.utils import get_cmd_cwd
ImportError: cannot import name 'get_cmd_cwd' from 'mlhub.utils' (/usr/local/lib/python3.9/dist-packages/mlhub/utils.py)

any ideas?

**Comment by gjwgit** [comment]
Thanks for reporting the issue.

Fixed with e3fe0f32839c02e334f15d2b63ff6365471a854d
